### ISSUE TITLE
Convert to LaTeX or similar

### ISSUE THREAD

**Issue by chances** [chances/resume#1]
The proprietary OS X Pages document format has been limiting. Converting the resume to LaTeX or another similar type setting solution should allow for greater flexibility.

**Solution must support:**

- Recreation of existing document near perfectly
- PDF output free of watermarks or other proprietary signs

**Todo**

- [ ] Investigate alternatives to LaTeX
- [ ] Choose a viable solution
- [ ] Convert the resume
